---
- include_vars: ../vars/vars.yml

- name:   Install packages
  become:        true
  become_user:   root
  become_method: sudo
  pacman: pkg={{ item }}
          state=present
  with_items: "{{ packages }}"

- name: Clone dotfiles
  git:  repo="https://github.com/urbanslug/dotfiles.git"
        clone=yes
        dest={{ dotfiles_dir }}

# https://gist.github.com/urbanslug/a5713e70496e3e82c8bec9d32737615f
- name: Ensure directories exist
  file: path={{ item }}
        state=directory
  with_items: "{{ dirs }}"

- name: Ensure symlinks exist
  file: src={{ item.key }}
        path={{ item.value }}
        state=link
  with_dict: "{{ symlinks }}"

- name: symlink /root/.zshrc
  become: true
  become_user: root
  become_method: sudo
  file: src={{ dotfiles_dir }}/.zshrc
        path=/root/.zshrc
        state=link

- name: Clone zsh-autosuggestions
  git:  repo="https://github.com/zsh-users/zsh-autosuggestions.git"
        clone=yes
        dest={{ zsh_dir }}/zsh-autosuggestions

- name: Clone zsh-syntax-highlighting
  git:  repo="https://github.com/zsh-users/zsh-syntax-highlighting.git"
        clone=yes
        dest={{ zsh_dir }}/zsh-syntax-highlighting

- name: Clone zsh-completions
  git:  repo="https://github.com/zsh-users/zsh-completions.git"
        clone=yes
        dest={{ zsh_dir }}/zsh-completions
