---
- name: Convert digital ocean debian to arch
  hosts: base
  remote_user: root

  tasks:
  - name:    Fetch arch install script.
    get_url: url=https://raw.githubusercontent.com/gh2o/digitalocean-debian-to-arch/debian8/install.sh
             dest=/root/install.sh

  - name: Install pip.
    apt: name=python-pip state=present

  - name: Install pexpect.
    pip: name=pexpect state=latest

  - name:   Install archlinux.
    expect:
      command: bash /root/install.sh
      responses:
        "Type \"wipe this droplet\" to continue or anything else to cancel.":  "wipe this droplet"
