---
- name: Convert digital ocean debian to arch
  hosts: digital-ocean
  remote_user: root

  tasks:
  - name:    Fetch arch install script.
    get_url: url=https://gist.githubusercontent.com/urbanslug/19f66c6692c0057fa40cbf09c721c629/raw/3b1d6543c8b7aa911f3b6016f7bcec30aabd0298/arch_install.sh
             dest=/root/arch_install.sh

  - name: Install archlinux.
    raw:  bash /root/arch_install.sh
