---
- name: Convert digital ocean debian to arch
  hosts: digital-ocean
  remote_user: root

  tasks:
  - name:    Fetch arch install script.
    get_url: url=https://raw.githubusercontent.com/gh2o/digitalocean-debian-to-arch/debian9/install.sh
             dest=/root/arch_install.sh

  - name: Install archlinux.
    raw:  bash /root/arch_install.sh --i_understand_that_this_droplet_will_be_completely_wiped
