- name: install nginx
  pacman: name=nginx
          state=present

- name: install certbot
  pacman: name=certbot
          state=present

- name: copy ssl_common.conf
  copy: src=../files/ssl_common.conf
        dest=/etc/nginx/ssl_common.conf
        owner=root
        group=root
        mode=0644

- name: copy nginx.conf file to the host.
  copy: src=../files/nginx.conf
        dest=/etc/nginx/nginx.conf
        owner=root
        group=root
        mode=0644
        backup=yes

- name: LetsEncrypt autpo renewal script
  copy: src=../files/certbot.service
        dest=/etc/systemd/system/certbot.service
        owner=root
        group=root
        mode=0644

- name: Certbot timer
  copy: src=../files/certbot.timer
        dest=/etc/systemd/system/certbot.timer
        owner=root
        group=root
        mode=0644

- name: Generate dhpharam.pem
  command: openssl dhparam -out /etc/nginx/dhparam.pem 4096

- name: Start certbot timer
  service: name=certbot.timer
           enabled=yes

- name: Start nginx at boot.
  service: name=nginx
           enabled=yes
