- name: install nginx
  pacman: name=nginx state=present

- name: install certbot
  pacman: name=certbot state=present

- name: copy nginx.conf file to the host.
  copy: src=../files/nginx/nginx.conf
        dest=/etc/nginx/nginx.conf
        owner=root
        group=root
        mode=0644
        backup=yes

- name: Start nginx at boot.
  service: name=nginx enabled=yes
